name: GitHubAction Job Schedule ETL from aqicn.org

on:
 schedule:
  - cron: '*/10 * * * *'

jobs:
  aqi_docker_container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{secrets.DOCKER_USERNAME}}
      #    password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build Dcoker image
        run: docker build -t aqi-img:latest
      
      - name: Run Docker Container
        run: |
          docker run \
            -e KEVIN_AQICN_KEY=${{secrets.KEVIN_AQICN_KEY}} \
            AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY}} \
            AWS_SECRET_KEY=${{secrets.AWS_SECRET_KEY}} \
            AWS_REGION_NAME=${{secrets.AWS_REGION_NAME}} \
            AWS_IAM_ROLE_ARN=${{secrets.AWS_IAM_ROLE_ARN}} \
            aqi-img:latest



