name: GitHubAction Job Schedule ETL from aqicn.org

on:
schedule:
    - cron: '00/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run aqicn ETL scheduled 
        run: python ./ETL/automate-feature-pipeline.py
