name: GitHubAction Job Schedule ETL from aqicn.org

on:
 schedule:
  - cron: '*/10 * * * *'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  aws_region_name: us-east-1
  role_to_assume: arn:aws:iam::${{ secrets.AWS_ACCNT_NO }}:role/kevin-aqi-proj-role
  role_session_name: kevin-store-aqi-session
  kevin_aqicn_key: ${{ secrets.KEVIN_AQICN_KEY }}

jobs:
  aqi_docker_container:    
      
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region_name }}
          role-to-assume: ${{ env.role_to_assume }}
          role-session-name: ${{ env.role_session_name }}
          output-credentials: true
      
      - name: get caller identity creds and session
        run: aws sts get-caller-identity
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # ---> unlock when building with docker buildx docker-container driver

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          #driver: docker

      #- name: test secrets
      #  run: |
      #    echo "this is  a test..."
      #    echo echo ${{secrets.KEVIN_AQICN_KEY}} | sed 's/./& /g'
      #    echo "end of testing..."
      
      #- name: Build Docker Image
      #  run: |
      #    docker build -t localhost:5000/aqi-img:latest \
      #    --build-arg KEVIN_AQICN_KEY= "${{ secrets.KEVIN_AQICN_KEY }}" \
      #    --build-arg AWS_ACCESS_KEY= "${{ secrets.AWS_ACCESS_KEY }}" \
      #    --build-arg AWS_SECRET_KEY= "${{ secrets.AWS_SECRET_KEY }}" \
      #    --build-arg AWS_REGION_NAME= "${{ secrets.AWS_REGION_NAME }}" \
      #    --build-arg AWS_IAM_ROLE_ARN= "${{ secrets.AWS_IAM_ROLE_ARN }}" \
      #    .
      
      #- name: Push Docker Image
      #  run: |
      #    docker image push localhost:5000/aqi-img:latest
      
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64           
          build-args: |
            KEVIN_AQICN_KEY= ${{ env.kevin_aqicn_key }}
            AWS_ACCESS_KEY= ${{ steps.creds.outputs.aws-access-key-id }}
            AWS_SECRET_KEY= ${{ steps.creds.outputs.aws-secret-access-key }}
            AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
            AWS_REGION_NAME= ${{ env.aws_region_name }}
          tags: localhost:5000/aqi-img:latest
          push: true


      - name: View Docker images
        run: |
          ls -la 
          docker images
          docker buildx imagetools inspect localhost:5000/aqi-img:latest

      - name: Run Docker Container
        run:
          docker run localhost:5000/aqi-img:latest
            

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{secrets.DOCKER_USERNAME}}
      #    password: ${{secrets.DOCKER_PASSWORD}}
      

      




