name: GitHubAction Job Schedule ETL from aqicn.org

on:
 schedule:
  - cron: '*/10 * * * *'
  

jobs:
  aqi_docker_container:      
      
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # ---> unlock when building with docker buildx docker-container driver

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          #driver: docker
      
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          environment: project-keys
          env: |
            key1: ${{ secrets.KEVIN_AQICN_KEY }}
            key2: ${{ secrets.AWS_ACCESS_KEY }}
          secrets: |
            KEVIN_AQICN_KEY: env.key1
            AWS_ACCESS_KEY= env.key2
            AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_KEY }}"
            "AWS_REGION_NAME=${{ secrets.AWS_REGION_NAME }}"
            "AWS_IAM_ROLE_ARN=${{ secrets.AWS_IAM_ROLE_ARN }}"
          tags: localhost:5000/aqi-img:latest
          push: true


      - name: View Docker images
        run: |
          ls -la 
          docker images
          docker buildx imagetools inspect localhost:5000/aqi-img:latest

      - name: Run Docker Container
        run:
          docker run localhost:5000/aqi-img:latest
            

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{secrets.DOCKER_USERNAME}}
      #    password: ${{secrets.DOCKER_PASSWORD}}
      

      




