name: GitHubAction Job Schedule ETL from aqicn.org

on:
 schedule:
  - cron: '*/10 * * * *'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  aws_region_name: us-east-1
  role_to_assume: arn:aws:iam::${{ secrets.AWS_ACCNT_NO }}:role/kevin-aqi-proj-role
  role_session_name: kevin-store-aqi-session
  kevin_aqicn_key: ${{ secrets.KEVIN_AQICN_KEY }}

jobs:
  aqi_docker_container:    
      
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region_name }}
          role-to-assume: ${{ env.role_to_assume }}
          role-session-name: ${{ env.role_session_name }}
          output-credentials: true
                  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # ---> unlock when building with docker buildx docker-container driver

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          #driver: docker
      
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64           
          build-args: |
            KEVIN_AQICN_KEY= ${{ env.kevin_aqicn_key }}
            AWS_ACCESS_KEY= ${{ steps.creds.outputs.aws-access-key-id }}
            AWS_SECRET_KEY= ${{ steps.creds.outputs.aws-secret-access-key }}
            AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
            AWS_REGION_NAME= ${{ env.aws_region_name }}
            AWS_ROLE_TO_ASSUME= ${{ env.role_to_assume }}
            AWS_ROLE_SESSION_NAME=${{ env.role_session_name}}
          tags: localhost:5000/aqi-img:latest
          push: true


      - name: Run Docker Container
        run:
          docker run localhost:5000/aqi-img:latest
            

      

      




